services:
  postgres:
    image: postgres:14
    container_name: areum-postgres
    environment:
      POSTGRES_USER: ${POSTGRES__DATABASE__USER}
      POSTGRES_PASSWORD: ${POSTGRES__DATABASE__PASSWORD}
      POSTGRES_DB: evolveme_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__DATABASE__USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: areum-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - APP_ENVIRONMENT=production
      - DATABASE_URL=postgres://${POSTGRES__DATABASE__USER}:${POSTGRES__DATABASE__PASSWORD}@postgres:5432/evolveme_db
      - POSTGRES__DATABASE__USER=${POSTGRES__DATABASE__USER}
      - POSTGRES__DATABASE__PASSWORD=${POSTGRES__DATABASE__PASSWORD}
      - APP__APPLICATION__USER=${APP__APPLICATION__USER}
      - APP__APPLICATION__PASSWORD=${APP__APPLICATION__PASSWORD}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data:
    name: areum-postgres-data